### ISSUE TITLE
Boolean values set to "false" are ignored

### ISSUE THREAD

**Issue by mgorniew** [Nerzal/gocloak#59] opened 2019-05-24 08:27 UTC
When I send request with bool field set to false, this field is not present in JSON.

```go
	keycloakClientUuid := uuid.New().String()
	keycloakClient := gocloak.Client{
		ID: keycloakClientUuid,
		ClientID: "test",
		Name: "test",
		Enabled: false,
	}
	if err := keycloak.CreateClient(token.AccessToken, "compaas", keycloakClient); err != nil {
		return "", err
	}
```

JSON send:

```json
{
  "clientId": "test",
  "id": "f522f163-2f7a-4857-a1da-5d4a21aa2b2c",
  "name": "test"
}
```

I believe that bool fields in models should be pointers.

**Comment by Nerzal** [comment] 2019-05-24 08:48
That's caused by omitempty flag.
But the important question is - does it work or is it broken? 

As these fields could default to false.

**Comment by mgorniew** [comment] 2019-05-24 09:21
Enabled field for Client defaults to true. So there is no way to change it false. And to support change from non-default to default value we need to be able to send value even if it matches default. Pointer should fix this. If you don't want to change value, you simple don't set - and nothing is send in JSON request.

**Comment by SVilgelm** [comment] 2019-05-24 12:07
yep, pointers should fix this, but it's backward incompatible and requires lots of work. But let's do it :)

**Comment by SVilgelm** [comment] 2019-05-26 13:25
Hmmm, please take a look at a commit: fdfc2774f68bd64f96e0032659628bb2463f124b
I changed the User's model to use pointers, but it looks awful. Probably we need to use different representations for create/update queries and responses. I don't like my solution and need your opinion or help.

@mgorniew @Nerzal ^^^

**Comment by SVilgelm** [comment] 2019-05-28 12:08
Guys, I need your opinion.

**Comment by SVilgelm** [comment] 2019-06-05 17:51
It's fixed in version 3

**Closed by SVilgelm** 2019-06-05 17:51 UTC
Labels: backward incompatible, bug
